### ISSUE TITLE
was wollen wir jetzt konkret machen und in welcem land fangen wir an?

### ISSUE THREAD

**Issue by C4reless** [C4reless/Fast-Food-simulator#2]

**Comment by C4reless** [comment]
besprechen wir morgen im raum

**Comment by danisanchezpoell** [comment]
lass in österreich beginnen, is am unkompliziertesten. Ich hab eher so an ein Spiel gedacht wo man cash verdient und man sozusagen den boss von dieser "Fast-Food Kette" ist.

**Comment by C4reless** [comment]
ja eh
aber halt so ein spiel wo du dein Imperium aufbauen musst 
mit coin System, gästen, bausystem und eben die länder
